define packageManager to avoid CloudFlare deployment error (build system v2 using pnpm@8.7.1)
......
Detected the following tools from environment: pnpm@8.7.1, nodejs@18.17.1
! The local project doesn't define a 'packageManager' field. Corepack will now add one referencing pnpm@8.7.1+sha512.41bb77121614697152da4e052d003baf6fde633fc9a03786ebcd3fdd45c6d066b4dcb3ee6381a076f08b7beccedcced99d61b8548e1b03093b4292727ebe5ea8.
! For more details about this field, consult the documentation at https://nodejs.org/api/packages.html#packagemanager
......
Installing project dependencies: pnpm install
 WARN  Ignoring not compatible lockfile at /opt/buildhome/repo/pnpm-lock.yaml
......
[config] Astro found issue(s) with your configuration:
! image.experimentalLayout: Invalid enum value. Expected 'constrained' | 'fixed' | 'full-width' | 'none', received 'responsive'
! experimental: Invalid or outdated experimental feature.
......
Error: Pagefind was not able to build an index.
Most likely, the directory passed to Pagefind was empty or did not contain any html files.